/**
 * Parsing for scanned QR payloads.
 *
 * Kept as .mjs so Node's built-in test runner can import it directly — the
 * project has no "type": "module", so a plain .js ESM file is not importable
 * outside the Next bundler. Next resolves .mjs fine.
 */

/** Longest payload we will still treat as a location code. */
const MAX_LOCATION_LENGTH = 64;

/**
 * Extracts a location ID from a scanned QR payload.
 *
 * Labels generated by lib/qr-service.js encode a full URL
 * (https://host/scan?location=BX-01-01), so the URL case is the norm. A bare
 * code is also accepted, since older or hand-made labels may encode just the
 * ID. Anything else — an unrelated URL, a WiFi QR, free text — returns null so
 * the caller can keep scanning instead of querying for a nonsense location.
 *
 * Returns an uppercase location ID, or null.
 */
export function parseLocationFromQr(text) {
  if (typeof text !== 'string') return null;

  const trimmed = text.trim();
  if (trimmed === '' || trimmed.length > MAX_LOCATION_LENGTH * 8) return null;

  // Case 1: a URL. Host is deliberately not checked — the same physical label
  // has to keep working across localhost, staging and production.
  try {
    const url = new URL(trimmed);
    const location = (url.searchParams.get('location') || '').trim();
    return location === '' ? null : normalize(location);
  } catch {
    // Not a URL; fall through to the bare-code case.
  }

  // Case 2: a bare location code. Whitespace or excessive length means this is
  // prose or some other payload, not a code.
  if (/\s/.test(trimmed)) return null;
  if (trimmed.length > MAX_LOCATION_LENGTH) return null;
  // A bare code must look like one. Deliberately permissive on the character
  // set (IDs are not validated at creation time) but it must start
  // alphanumeric, which rules out things like "WIFI:S:..." and ";;".
  if (!/^[A-Za-z0-9][A-Za-z0-9._/-]*$/.test(trimmed)) return null;

  return normalize(trimmed);
}

function normalize(value) {
  const upper = value.trim().toUpperCase();
  return upper.length > MAX_LOCATION_LENGTH ? null : upper;
}
